# fly.toml app configuration file generated for totalenergies-charging-solutions-api on 2026-06-22T19:58:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'totalenergies-charging-solutions-api'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
